//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.model_new
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClubPolideportivoDBEntities : DbContext
    {
        public ClubPolideportivoDBEntities()
            : base("name=ClubPolideportivoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuotas> Cuotas { get; set; }
        public virtual DbSet<Instalaciones> Instalaciones { get; set; }
        public virtual DbSet<PagosReserva> PagosReserva { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Socios> Socios { get; set; }
        public virtual DbSet<TiposInstalacion> TiposInstalacion { get; set; }
    }
}
