//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.model_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuotas
    {
        public int CuotaId { get; set; }
        public int SocioId { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public bool Pagada { get; set; }
    
        public virtual Socios Socios { get; set; }
    }
}
