//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.model_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instalaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instalaciones()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int InstalacionId { get; set; }
        public int TipoInstalacionId { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioHora { get; set; }
        public bool Disponible { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TiposInstalacion TiposInstalacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
