//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.model_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.PagosReserva = new HashSet<PagosReserva>();
        }
    
        public int ReservaId { get; set; }
        public int SocioId { get; set; }
        public int InstalacionId { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public System.DateTime FechaHoraFin { get; set; }
        public decimal PrecioTotal { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Instalaciones Instalaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosReserva> PagosReserva { get; set; }
        public virtual Socios Socios { get; set; }
    }
}
