//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ofertas()
        {
            this.Operaciones = new HashSet<Operaciones>();
        }
    
        public int IdOferta { get; set; }
        public int IdCliente { get; set; }
        public int IdAgente { get; set; }
        public int IdInmueble { get; set; }
        public decimal PrecioOfertado { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaOferta { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Agentes Agentes { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Inmuebles Inmuebles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operaciones> Operaciones { get; set; }
    }
}
