var searchData=
[
  ['action_0',['Action',['../class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_row_change_event.html#a63664c565e1d71cc730f9f1f1a253edd',1,'ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoRowChangeEvent.Action'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_row_change_event.html#a0c4a9425e45bc6b0fe43dbbf204601ac',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaRowChangeEvent.Action'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___row_change_event.html#ad2854b10fbc498df2b15f9be820b8718',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_RowChangeEvent.Action'],['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_row_change_event.html#a29a18d9d8f48238f8e54037778dafcdd',1,'ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosRowChangeEvent.Action']]],
  ['activo_1',['Activo',['../class_proyecto_final_1_1model__new_1_1_socios.html#acc9e5a9a7eef15f86c046744b9b040ef',1,'ProyectoFinal::model_new::Socios']]],
  ['addingresosportiporow_2',['AddIngresosPorTipoRow',['../class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_data_table.html#a78ef07e7b4222896c8c1c3a376e126b8',1,'ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoDataTable.AddIngresosPorTipoRow(IngresosPorTipoRow row)'],['../class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_data_table.html#a16e5db37e47f543c8aefd6db55ae516b',1,'ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoDataTable.AddIngresosPorTipoRow(int TipoInstalacionId, string NombreTipo, int NumReservas, decimal TotalIngresos, decimal MediaPorReserva)']]],
  ['addreservasporfecharow_3',['AddReservasPorFechaRow',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html#aad7ba06bd0055bc3b7d0fee1d29ac241',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataTable.AddReservasPorFechaRow(ReservasPorFechaRow row)'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html#aa080142fbe13579c55d5c07081714955',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataTable.AddReservasPorFechaRow(int ReservaId, System.DateTime FechaHoraInicio, System.DateTime FechaHoraFin, string NombreSocio, string NombreInstalacion, decimal PrecioTotal, string Estado)']]],
  ['addreservasporinstalacion_5frow_4',['AddReservasPorInstalacion_Row',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html#a8aa003fb158efd1f470788d64084b4ab',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_DataTable.AddReservasPorInstalacion_Row(ReservasPorInstalacion_Row row)'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html#aaec177bab18f4ac00a47fd37e4ef84ff',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_DataTable.AddReservasPorInstalacion_Row(int ReservaId, string NombreInstalacion, string NombreSocio, System.DateTime FechaHoraInicio, System.DateTime FechaHoraFin, decimal PrecioTotal, string Estado)']]],
  ['addsociosactivosrow_5',['AddSociosActivosRow',['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_data_table.html#a13a3a69994898d0651c37a3382a0c24d',1,'ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosDataTable.AddSociosActivosRow(SociosActivosRow row)'],['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_data_table.html#a1c3f118448f1b9961203b2048ca45cee',1,'ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosDataTable.AddSociosActivosRow(int SocioId, string Nombre, string Apellidos, string DNI, string Telefono, string Email, System.DateTime FechaAlta)']]],
  ['and_20support_6',['Status and Support',['../dir_8f8b4e775bf3243cd37998a57f703cfe.html#autotoc_md1',1,'']]],
  ['anio_7',['Anio',['../class_proyecto_final_1_1model__new_1_1_cuotas.html#a015c61f5c00f29faecc1e3e856a959fd',1,'ProyectoFinal::model_new::Cuotas']]],
  ['apellidos_8',['Apellidos',['../class_proyecto_final_1_1model__new_1_1_socios.html#a7d6d49c633806a6e59bff0940003bc5b',1,'ProyectoFinal.model_new.Socios.Apellidos'],['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_row.html#ab4536a8cd8909863af9d1cd6f761923c',1,'ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosRow.Apellidos']]],
  ['apellidoscolumn_9',['ApellidosColumn',['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_data_table.html#af80e25d3ef373e325fb3d8a5f5906d81',1,'ProyectoFinal::Reports_new::SociosActivosDataSet::SociosActivosDataTable']]],
  ['app_10',['App',['../class_proyecto_final_1_1_reports_view__new_1_1_app.html',1,'ProyectoFinal.ReportsView_new.App'],['../class_proyecto_final_1_1view__new_1_1_app.html',1,'ProyectoFinal.view_new.App']]],
  ['app_2eg_2ecs_11',['App.g.cs',['../_proyecto_final_8_reports_view__new_2obj_2x86_2_debug_2_app_8g_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8_reports_view__new_2obj_2x86_2_release_2_app_8g_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2_release_2_app_8g_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2x86_2_debug_2_app_8g_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2x86_2_release_2_app_8g_8cs.html',1,'(Espacio de nombres global)']]],
  ['app_2eg_2ei_2ecs_12',['App.g.i.cs',['../_proyecto_final_8_reports_view__new_2obj_2x86_2_debug_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8_reports_view__new_2obj_2x86_2_release_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2_release_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2x86_2_debug_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2obj_2x86_2_release_2_app_8g_8i_8cs.html',1,'(Espacio de nombres global)']]],
  ['app_2examl_2ecs_13',['App.xaml.cs',['../_proyecto_final_8_reports_view__new_2_app_8xaml_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2_app_8xaml_8cs.html',1,'(Espacio de nombres global)']]],
  ['assemblyinfo_2ecs_14',['AssemblyInfo.cs',['../_comun_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8controller__new_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8model__new_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8_reports__new_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8_reports_view__new_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)'],['../_proyecto_final_8view__new_2_properties_2_assembly_info_8cs.html',1,'(Espacio de nombres global)']]],
  ['autoregisteredextensions_2ecs_15',['AutoRegisteredExtensions.cs',['../_debug_2net48_2_auto_registered_extensions_8cs.html',1,'(Espacio de nombres global)'],['../_release_2net48_2_auto_registered_extensions_8cs.html',1,'(Espacio de nombres global)'],['../x86_2_debug_2net48_2_auto_registered_extensions_8cs.html',1,'(Espacio de nombres global)'],['../x86_2_release_2net48_2_auto_registered_extensions_8cs.html',1,'(Espacio de nombres global)']]]
];
