var searchData=
[
  ['readxmlserializable_0',['ReadXmlSerializable',['../class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set.html#a8ff6433322f9bd17d36bb6018b6ad445',1,'ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.ReadXmlSerializable()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set.html#adbde55d6c8091c52585be4ce4337d33e',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReadXmlSerializable()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set.html#a009ea34ec36de563823da4dbf639f40f',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReadXmlSerializable()'],['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set.html#abf62dc1fd8af26e96d05813ada4092d9',1,'ProyectoFinal.Reports_new.SociosActivosDataSet.ReadXmlSerializable()']]],
  ['removeingresosportiporow_1',['RemoveIngresosPorTipoRow',['../class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_data_table.html#afa08233698547fd1e13dbb8ed9767890',1,'ProyectoFinal::Reports_new::IngresosPorTipoInstalacionDataSet::IngresosPorTipoDataTable']]],
  ['removereservasporfecharow_2',['RemoveReservasPorFechaRow',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html#a90def2b00b116739d1ec24e36810c9a2',1,'ProyectoFinal::Reports_new::ReservasPorFechaDataSet::ReservasPorFechaDataTable']]],
  ['removereservasporinstalacion_5frow_3',['RemoveReservasPorInstalacion_Row',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html#aadf4c8a260fa39b8a498c83d84793645',1,'ProyectoFinal::Reports_new::ReservasPorInstalacionDataSet::ReservasPorInstalacion_DataTable']]],
  ['removesociosactivosrow_4',['RemoveSociosActivosRow',['../class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_data_table.html#aabff9e45e30b63dd82fd32a0ce2be1f2',1,'ProyectoFinal::Reports_new::SociosActivosDataSet::SociosActivosDataTable']]],
  ['repositorybase_5',['RepositoryBase',['../class_proyecto_final_1_1model__new_1_1_repository_base.html#a7430f68f32037460338c89e22e992f8e',1,'ProyectoFinal::model_new::RepositoryBase']]],
  ['reservas_6',['Reservas',['../class_proyecto_final_1_1model__new_1_1_reservas.html#a4f15a4d12b6573ed9e6a121e0e216b2b',1,'ProyectoFinal::model_new::Reservas']]],
  ['reservasapi_7',['ReservasAPI',['../class_proyecto_final_1_1controller__new_1_1api_1_1_reservas_a_p_i.html#a21d8ce357174e644ef40ca51350e7bc9',1,'ProyectoFinal::controller_new::api::ReservasAPI']]],
  ['reservascontroller_8',['ReservasController',['../class_proyecto_final_1_1controller__new_1_1controller_1_1_reservas_controller.html#af39235c6e5d48d8cebfcb0c0f59e08a3',1,'ProyectoFinal::controller_new::controller::ReservasController']]],
  ['reservasporfechadataset_9',['ReservasPorFechaDataSet',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set.html#ab8c4690a4b13785987ffb4e17e6a48aa',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataSet()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set.html#add004b05d080c6c4731ff1b8b8587007',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['reservasporfechadatatable_10',['ReservasPorFechaDataTable',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html#a825531ad4757178728229f0988a83293',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataTable.ReservasPorFechaDataTable()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html#a7ae4e4661a8cc3d901b972a40308f774',1,'ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataTable.ReservasPorFechaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['reservasporfechareportbuilder_11',['ReservasPorFechaReportBuilder',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_report_builder.html#abce2c2688a5dba007caec5f04fd0605f',1,'ProyectoFinal::Reports_new::ReservasPorFechaReportBuilder']]],
  ['reservasporfecharowchangeevent_12',['ReservasPorFechaRowChangeEvent',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_row_change_event.html#a07f301dd2becadacb661d32585091cc1',1,'ProyectoFinal::Reports_new::ReservasPorFechaDataSet::ReservasPorFechaRowChangeEvent']]],
  ['reservasporfecharowchangeeventhandler_13',['ReservasPorFechaRowChangeEventHandler',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set.html#ac04fec2f4439bbddfeb175297648516e',1,'ProyectoFinal::Reports_new::ReservasPorFechaDataSet']]],
  ['reservasporinstalacion_5fdatatable_14',['ReservasPorInstalacion_DataTable',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html#add3835c3942f21052a7b852505ef568d',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_DataTable.ReservasPorInstalacion_DataTable()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html#afd7553b10bbc847ce2f8f159609d2646',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_DataTable.ReservasPorInstalacion_DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['reservasporinstalacion_5frowchangeevent_15',['ReservasPorInstalacion_RowChangeEvent',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___row_change_event.html#a94d0b28a96ddde2aa7dea1b72572e236',1,'ProyectoFinal::Reports_new::ReservasPorInstalacionDataSet::ReservasPorInstalacion_RowChangeEvent']]],
  ['reservasporinstalacion_5frowchangeeventhandler_16',['ReservasPorInstalacion_RowChangeEventHandler',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set.html#a70aa977bbb3e652051dea8d904db67d4',1,'ProyectoFinal::Reports_new::ReservasPorInstalacionDataSet']]],
  ['reservasporinstalaciondataset_17',['ReservasPorInstalacionDataSet',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set.html#abecdec5d87ad081b4934882fb949ffca',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacionDataSet()'],['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set.html#ac8d5d11628c5bd20ddd5df74ead5dbbf',1,'ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacionDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['reservasporinstalacionreportbuilder_18',['ReservasPorInstalacionReportBuilder',['../class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_report_builder.html#a68e71975e7f93b4dcd6d8f722cc86839',1,'ProyectoFinal::Reports_new::ReservasPorInstalacionReportBuilder']]]
];
