var _informe_ingresos_por_tipo_instalacion_8cs =
[
    [ "ProyectoFinal.Reports_new.InformeIngresosPorTipoInstalacion", "class_proyecto_final_1_1_reports__new_1_1_informe_ingresos_por_tipo_instalacion.html", "class_proyecto_final_1_1_reports__new_1_1_informe_ingresos_por_tipo_instalacion" ],
    [ "ProyectoFinal.Reports_new.CachedInformeIngresosPorTipoInstalacion", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_ingresos_por_tipo_instalacion.html", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_ingresos_por_tipo_instalacion" ]
];