var _reservas_por_instalacion_report_builder_8cs =
[
    [ "ProyectoFinal.Reports_new.ReservasPorInstalacionReportBuilder", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_report_builder.html", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_report_builder" ]
];