var dir_32050204d26431a1646f02ca79a5c3c5 =
[
    [ ".NETFramework,Version=v4.8.AssemblyAttributes.cs", "_proyecto_final_8view__new_2obj_2_debug_2_8_n_e_t_framework_00_version_0av4_88_8_assembly_attributes_8cs.html", null ],
    [ "App.g.cs", "_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8cs.html", "_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8cs" ],
    [ "App.g.i.cs", "_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8i_8cs.html", "_proyecto_final_8view__new_2obj_2_debug_2_app_8g_8i_8cs" ],
    [ "MainWindow.g.cs", "_debug_2_main_window_8g_8cs.html", "_debug_2_main_window_8g_8cs" ],
    [ "MainWindow.g.i.cs", "_debug_2_main_window_8g_8i_8cs.html", "_debug_2_main_window_8g_8i_8cs" ],
    [ "ModalBuscarInstalacion.g.cs", "_debug_2_modal_buscar_instalacion_8g_8cs.html", "_debug_2_modal_buscar_instalacion_8g_8cs" ],
    [ "ModalBuscarInstalacion.g.i.cs", "_debug_2_modal_buscar_instalacion_8g_8i_8cs.html", "_debug_2_modal_buscar_instalacion_8g_8i_8cs" ],
    [ "ModalBuscarSocio.g.cs", "_debug_2_modal_buscar_socio_8g_8cs.html", "_debug_2_modal_buscar_socio_8g_8cs" ],
    [ "ModalBuscarSocio.g.i.cs", "_debug_2_modal_buscar_socio_8g_8i_8cs.html", "_debug_2_modal_buscar_socio_8g_8i_8cs" ],
    [ "ModalNuevaReserva.g.cs", "_debug_2_modal_nueva_reserva_8g_8cs.html", "_debug_2_modal_nueva_reserva_8g_8cs" ],
    [ "ModalNuevaReserva.g.i.cs", "_debug_2_modal_nueva_reserva_8g_8i_8cs.html", "_debug_2_modal_nueva_reserva_8g_8i_8cs" ],
    [ "VistaCuotas.g.cs", "_debug_2_vista_cuotas_8g_8cs.html", "_debug_2_vista_cuotas_8g_8cs" ],
    [ "VistaCuotas.g.i.cs", "_debug_2_vista_cuotas_8g_8i_8cs.html", "_debug_2_vista_cuotas_8g_8i_8cs" ],
    [ "VistaInformes.g.cs", "_debug_2_vista_informes_8g_8cs.html", "_debug_2_vista_informes_8g_8cs" ],
    [ "VistaInformes.g.i.cs", "_debug_2_vista_informes_8g_8i_8cs.html", "_debug_2_vista_informes_8g_8i_8cs" ],
    [ "VistaInicio.g.cs", "_debug_2_vista_inicio_8g_8cs.html", "_debug_2_vista_inicio_8g_8cs" ],
    [ "VistaInicio.g.i.cs", "_debug_2_vista_inicio_8g_8i_8cs.html", "_debug_2_vista_inicio_8g_8i_8cs" ],
    [ "VistaInstalaciones.g.cs", "_debug_2_vista_instalaciones_8g_8cs.html", "_debug_2_vista_instalaciones_8g_8cs" ],
    [ "VistaInstalaciones.g.i.cs", "_debug_2_vista_instalaciones_8g_8i_8cs.html", "_debug_2_vista_instalaciones_8g_8i_8cs" ],
    [ "VistaReservas.g.cs", "_debug_2_vista_reservas_8g_8cs.html", "_debug_2_vista_reservas_8g_8cs" ],
    [ "VistaReservas.g.i.cs", "_debug_2_vista_reservas_8g_8i_8cs.html", "_debug_2_vista_reservas_8g_8i_8cs" ],
    [ "VistaSocios.g.cs", "_debug_2_vista_socios_8g_8cs.html", "_debug_2_vista_socios_8g_8cs" ],
    [ "VistaSocios.g.i.cs", "_debug_2_vista_socios_8g_8i_8cs.html", "_debug_2_vista_socios_8g_8i_8cs" ],
    [ "VistaTiposInstalacion.g.cs", "_debug_2_vista_tipos_instalacion_8g_8cs.html", "_debug_2_vista_tipos_instalacion_8g_8cs" ],
    [ "VistaTiposInstalacion.g.i.cs", "_debug_2_vista_tipos_instalacion_8g_8i_8cs.html", "_debug_2_vista_tipos_instalacion_8g_8i_8cs" ],
    [ "win_modal_message.g.cs", "_debug_2win__modal__message_8g_8cs.html", "_debug_2win__modal__message_8g_8cs" ],
    [ "win_modal_message.g.i.cs", "_debug_2win__modal__message_8g_8i_8cs.html", "_debug_2win__modal__message_8g_8i_8cs" ]
];