var hierarchy =
[
    [ "Application", null, [
      [ "ProyectoFinal.ReportsView_new.App", "class_proyecto_final_1_1_reports_view__new_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Application", null, [
      [ "ProyectoFinal.ReportsView_new.App", "class_proyecto_final_1_1_reports_view__new_1_1_app.html", null ],
      [ "ProyectoFinal.ReportsView_new.App", "class_proyecto_final_1_1_reports_view__new_1_1_app.html", null ],
      [ "ProyectoFinal.ReportsView_new.App", "class_proyecto_final_1_1_reports_view__new_1_1_app.html", null ],
      [ "ProyectoFinal.ReportsView_new.App", "class_proyecto_final_1_1_reports_view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ],
      [ "ProyectoFinal.view_new.App", "class_proyecto_final_1_1view__new_1_1_app.html", null ]
    ] ],
    [ "Component", null, [
      [ "ProyectoFinal.Reports_new.CachedInformeIngresosPorTipoInstalacion", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_ingresos_por_tipo_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeReservasPorFecha", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_reservas_por_fecha.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeReservasPorInstalacion", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_reservas_por_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeSociosActivos", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_socios_activos.html", null ]
    ] ],
    [ "ProyectoFinal.model_new.Cuotas", "class_proyecto_final_1_1model__new_1_1_cuotas.html", null ],
    [ "ProyectoFinal.controller_new.api.CuotasAPI", "class_proyecto_final_1_1controller__new_1_1api_1_1_cuotas_a_p_i.html", null ],
    [ "ProyectoFinal.controller_new.controller.CuotasController", "class_proyecto_final_1_1controller__new_1_1controller_1_1_cuotas_controller.html", null ],
    [ "global.SystemData.DataRow", null, [
      [ "ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoRow", "class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_row.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaRow", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_row.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_Row", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___row.html", null ],
      [ "ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosRow", "class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_row.html", null ]
    ] ],
    [ "global.SystemData.DataSet", null, [
      [ "ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet", "class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorFechaDataSet", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set.html", null ],
      [ "ProyectoFinal.Reports_new.SociosActivosDataSet", "class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set.html", null ]
    ] ],
    [ "DbContext", null, [
      [ "ProyectoFinal.model_new.ClubPolideportivoDBEntities", "class_proyecto_final_1_1model__new_1_1_club_polideportivo_d_b_entities.html", null ]
    ] ],
    [ "ProyectoFinal.view_new.HuecoDiario", "class_proyecto_final_1_1view__new_1_1_hueco_diario.html", null ],
    [ "ICachedReport", null, [
      [ "ProyectoFinal.Reports_new.CachedInformeIngresosPorTipoInstalacion", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_ingresos_por_tipo_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeReservasPorFecha", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_reservas_por_fecha.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeReservasPorInstalacion", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_reservas_por_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.CachedInformeSociosActivos", "class_proyecto_final_1_1_reports__new_1_1_cached_informe_socios_activos.html", null ]
    ] ],
    [ "System.Windows.Markup.IComponentConnector", null, [
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ]
    ] ],
    [ "ProyectoFinal.Reports_new.IngresosPorTipoInstalacionReportBuilder", "class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_report_builder.html", null ],
    [ "ProyectoFinal.model_new.Instalaciones", "class_proyecto_final_1_1model__new_1_1_instalaciones.html", null ],
    [ "ProyectoFinal.controller_new.api.InstalacionesAPI", "class_proyecto_final_1_1controller__new_1_1api_1_1_instalaciones_a_p_i.html", null ],
    [ "ProyectoFinal.controller_new.controller.InstalacionesController", "class_proyecto_final_1_1controller__new_1_1controller_1_1_instalaciones_controller.html", null ],
    [ "IValueConverter", null, [
      [ "Comun.PrecioConverter", "class_comun_1_1_precio_converter.html", null ]
    ] ],
    [ "ProyectoFinal.model_new.PagosReserva", "class_proyecto_final_1_1model__new_1_1_pagos_reserva.html", null ],
    [ "ReportClass", null, [
      [ "ProyectoFinal.Reports_new.InformeIngresosPorTipoInstalacion", "class_proyecto_final_1_1_reports__new_1_1_informe_ingresos_por_tipo_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.InformeReservasPorFecha", "class_proyecto_final_1_1_reports__new_1_1_informe_reservas_por_fecha.html", null ],
      [ "ProyectoFinal.Reports_new.InformeReservasPorInstalacion", "class_proyecto_final_1_1_reports__new_1_1_informe_reservas_por_instalacion.html", null ],
      [ "ProyectoFinal.Reports_new.InformeSociosActivos", "class_proyecto_final_1_1_reports__new_1_1_informe_socios_activos.html", null ]
    ] ],
    [ "ProyectoFinal.model_new.RepositoryBase", "class_proyecto_final_1_1model__new_1_1_repository_base.html", [
      [ "ProyectoFinal.model_new.Repositories.CuotasRepository", "class_proyecto_final_1_1model__new_1_1_repositories_1_1_cuotas_repository.html", null ],
      [ "ProyectoFinal.model_new.Repositories.InstalacionesRepository", "class_proyecto_final_1_1model__new_1_1_repositories_1_1_instalaciones_repository.html", null ],
      [ "ProyectoFinal.model_new.Repositories.ReservasRepository", "class_proyecto_final_1_1model__new_1_1_repositories_1_1_reservas_repository.html", null ],
      [ "ProyectoFinal.model_new.Repositories.SociosRepository", "class_proyecto_final_1_1model__new_1_1_repositories_1_1_socios_repository.html", null ],
      [ "ProyectoFinal.model_new.Repositories.TiposInstalacionRepository", "class_proyecto_final_1_1model__new_1_1_repositories_1_1_tipos_instalacion_repository.html", null ]
    ] ],
    [ "ProyectoFinal.model_new.Reservas", "class_proyecto_final_1_1model__new_1_1_reservas.html", null ],
    [ "ProyectoFinal.controller_new.api.ReservasAPI", "class_proyecto_final_1_1controller__new_1_1api_1_1_reservas_a_p_i.html", null ],
    [ "ProyectoFinal.controller_new.controller.ReservasController", "class_proyecto_final_1_1controller__new_1_1controller_1_1_reservas_controller.html", null ],
    [ "ProyectoFinal.Reports_new.ReservasPorFechaReportBuilder", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_report_builder.html", null ],
    [ "ProyectoFinal.Reports_new.ReservasPorInstalacionReportBuilder", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_report_builder.html", null ],
    [ "ProyectoFinal.model_new.Socios", "class_proyecto_final_1_1model__new_1_1_socios.html", null ],
    [ "ProyectoFinal.Reports_new.SociosActivosReportBuilder", "class_proyecto_final_1_1_reports__new_1_1_socios_activos_report_builder.html", null ],
    [ "ProyectoFinal.controller_new.api.SociosAPI", "class_proyecto_final_1_1controller__new_1_1api_1_1_socios_a_p_i.html", null ],
    [ "ProyectoFinal.controller_new.controller.SociosController", "class_proyecto_final_1_1controller__new_1_1controller_1_1_socios_controller.html", null ],
    [ "global.SystemEventArgs", null, [
      [ "ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoRowChangeEvent", "class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_row_change_event.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaRowChangeEvent", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_row_change_event.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_RowChangeEvent", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___row_change_event.html", null ],
      [ "ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosRowChangeEvent", "class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_row_change_event.html", null ]
    ] ],
    [ "ProyectoFinal.test.Test1", "class_proyecto_final_1_1test_1_1_test1.html", null ],
    [ "ProyectoFinal.model_new.TiposInstalacion", "class_proyecto_final_1_1model__new_1_1_tipos_instalacion.html", null ],
    [ "ProyectoFinal.controller_new.api.TiposInstalacionAPI", "class_proyecto_final_1_1controller__new_1_1api_1_1_tipos_instalacion_a_p_i.html", null ],
    [ "ProyectoFinal.controller_new.controller.TiposInstalacionController", "class_proyecto_final_1_1controller__new_1_1controller_1_1_tipos_instalacion_controller.html", null ],
    [ "global.SystemData.TypedTableBase", null, [
      [ "ProyectoFinal.Reports_new.IngresosPorTipoInstalacionDataSet.IngresosPorTipoDataTable", "class_proyecto_final_1_1_reports__new_1_1_ingresos_por_tipo_instalacion_data_set_1_1_ingresos_por_tipo_data_table.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorFechaDataSet.ReservasPorFechaDataTable", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_fecha_data_set_1_1_reservas_por_fecha_data_table.html", null ],
      [ "ProyectoFinal.Reports_new.ReservasPorInstalacionDataSet.ReservasPorInstalacion_DataTable", "class_proyecto_final_1_1_reports__new_1_1_reservas_por_instalacion_data_set_1_1_reservas_por_instalacion___data_table.html", null ],
      [ "ProyectoFinal.Reports_new.SociosActivosDataSet.SociosActivosDataTable", "class_proyecto_final_1_1_reports__new_1_1_socios_activos_data_set_1_1_socios_activos_data_table.html", null ]
    ] ],
    [ "System.Windows.Controls.UserControl", null, [
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaCuotas", "class_proyecto_final_1_1view__new_1_1_vista_cuotas.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInformes", "class_proyecto_final_1_1view__new_1_1_vista_informes.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInicio", "class_proyecto_final_1_1view__new_1_1_vista_inicio.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaInstalaciones", "class_proyecto_final_1_1view__new_1_1_vista_instalaciones.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaReservas", "class_proyecto_final_1_1view__new_1_1_vista_reservas.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaSocios", "class_proyecto_final_1_1view__new_1_1_vista_socios.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ],
      [ "ProyectoFinal.view_new.VistaTiposInstalacion", "class_proyecto_final_1_1view__new_1_1_vista_tipos_instalacion.html", null ]
    ] ],
    [ "Comun.Utils", "class_comun_1_1_utils.html", null ],
    [ "System.Windows.Window", null, [
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.ReportsView_new.Window1", "class_proyecto_final_1_1_reports_view__new_1_1_window1.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.MainWindow", "class_proyecto_final_1_1view__new_1_1_main_window.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarInstalacion", "class_proyecto_final_1_1view__new_1_1_modal_buscar_instalacion.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalBuscarSocio", "class_proyecto_final_1_1view__new_1_1_modal_buscar_socio.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.ModalNuevaReserva", "class_proyecto_final_1_1view__new_1_1_modal_nueva_reserva.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ],
      [ "ProyectoFinal.view_new.win_modal_message", "class_proyecto_final_1_1view__new_1_1win__modal__message.html", null ]
    ] ]
];